config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :chat_data do
   collection do
    get 'get_chat_images'
    get 'get_user_profile'
    get 'update_conv_status'
    get 'get_project_phase'
   end
 end

 resources :tags
 resources :products
 resources :fav_products do
   collection do
    get 'remove_fav_prod'
   end
 end
 resources :huzzpa_works

 resources :blogs do
   collection do
     get 'get_blogby_category'
     get 'get_latest_blogs'
     get 'get_blogby_type'
     get 'admin_blog'
     get 'template'
   end
 end

 resources :comments, only: [:index, :create , :destroy]
 get '/comments/new/:parent_id', to: 'comments#new', as: :new_comment
 get '/comments/reply', to: 'comments#reply'

  get 'design/modular-kitchen-designers', to: 'design_inspiration#kitchen'
  get 'design-inspiration/kitchen' => redirect('design/modular-kitchen-designers')

  get 'design/modular-wardrobe-designers', to: 'design_inspiration#wardrobes'
  get 'design-inspiration/bed-room' => redirect('design/modular-wardrobe-designers')
  get 'design-inspiration/bed' => redirect('design/modular-wardrobe-designers')
  get 'design-inspiration/wardrobes' => redirect('design/modular-wardrobe-designers')

  get 'design/shoe-cabinet-designers', to: 'design_inspiration#shoe_cabinet'
  get 'design-inspiration/shoe-cabinet' => redirect('design/shoe-cabinet-designers')

  get 'design/study-unit-designers', to: 'design_inspiration#study'
  get 'design-inspiration/study-unit' => redirect('design/study-unit-designers')
  get 'design-inspiration/study' => redirect('design/study-unit-designers')

  get 'design/vanity-unit-designers', to: 'design_inspiration#vanity_unit'
  get 'design-inspiration/bath-room' => redirect('design/vanity-unit-designers')
  get 'design-inspiration/vanity-unit' => redirect('design/vanity-unit-designers')

  get 'design/tv-unit-designers', to: 'design_inspiration#tv_unit'
  get 'design-inspiration/living-room' => redirect('design/tv-unit-designers')
  get 'design-inspiration/tv-unit' => redirect('design/tv-unit-designers')

  get 'design/crockery-unit-designers', to: 'design_inspiration#crockery_unit'
  get 'design-inspiration/dining' => redirect('design/crockery-unit-designers')
  get 'design-inspiration/crockery-unit' => redirect('design/crockery-unit-designers')

  get 'design-inspiration/wall-treatment' => redirect('/')
  get 'design-inspiration/kids-bedroom' => redirect('/')
  get 'design-inspiration/balcony' => redirect('/')

  get '/questioners/get_category_item/:category_id',      to: 'questioners#get_category_item'

  get '/user_preferences/get_question/:current_seq_no',      to: 'user_preferences#get_question'

  get '/user_preferences/get_interest_questions',      to: 'user_preferences#get_interest_questions'

  get '/user_preferences/get_next_interest_question',      to: 'user_preferences#get_next_interest_question'

  get '/user_preferences/update_user_interest',      to: 'user_preferences#update_user_interest'

  get '/user_preferences/get_client_requirement',      to: 'user_preferences#get_client_requirement'

  post "question_sequences/activate_questions" => "question_sequences#activate_questions"

  post "question_sequences/deactivate_questions" => "question_sequences#deactivate_questions"

  get "question_sequences/update_sequence" => "question_sequences#update_sequence"

  get "chat_accesses/update_status" => "chat_accesses#update_status"

  get"matched_vendors/chat_request" => "matched_vendors@chat_request"

  get 'matched_vendors/:tab' => 'matched_vendors#index' , as: 'matched_recommendations'

  resources :admins do
    collection do
      get 'vendors'
      get 'status'
      get 'new_vendor'
      post 'create_vendor'
      get 'users'
      get 'unblock'
      get 'guests'
      get 'export_users'
      get 'export_vendors'
      get 'get_user_profile'
    end
  end

  resources :users, only: [] do
    collection do
      resources :preferences, only: [:index, :create], controller: 'user_preferences' do
        collection do
          get 'select'
          get 'selected'
        end
      end
    end
  end
  resources :vendor_preferences, only: [:index, :create] do
    collection do
      get 'select'
      get 'selected'
    end
  end

  resources :vendor_works do
    collection do
      get 'portfolio_images'
      get 'all'
    end
  end

  resources :matched_vendors do
    collection do
      post 'connect'
      post 'get_product_filter_by_categ'
    end
  end

  resources :matched_users do
    collection do
      post 'connect'
    end
  end

  resources :user_profiles, except: [:new]
  resources :vendor_profiles, except: [:new] do
    collection do
      get 'public/:id', to: 'vendor_profiles#public_profile', as: 'public'
    end
  end
  resources :types, except: [:show]
  resources :category_items, except: [:show]
  resources :categories
  resources :questions
  resources :questioners
  resources :user_interests
  resources :user_details
  resources :questioners
  resources :question_sequences
  resources :chat_accesses

  devise_for :users, controllers: {registrations: :registrations, sessions: "sessions",
                      omniauth_callbacks: 'omniauth_callbacks'}

  resources :guests

  root 'home#index'
  get 'about', to: 'home#about'
  get 'interior_designers_mumbai', to: 'home#designer_mumbai' , as: 'interior-designers-mumbai' ,  path: "interior-designers-mumbai"
  get 'mumbai' => redirect('interior-designers-mumbai')
  get 'interior_designers_mumbai' => redirect('interior-designers-mumbai')

  get 'our-portfolio', to: 'home#profile'
  get 'profile' => redirect('our-portfolio')
  post 'contact', to: 'home#contact_us'
  get 'privacy', to: 'home#privacy'
  get 'terms', to: 'home#terms'
  get 'faq', to: 'home#faq'
  get 'user-role', to: 'home#user_role'
  get 'vendor-role', to: 'home#vendor_role'
  get 'contact-us', to: 'home#contact'
  get 'contact_us' => redirect('contact-us')
  post 'subscribe', to: 'home#subscribe', as: :subscribe

  resources :activate_vendors do
    collection do
      get 'contact_admin'
    end
  end

  resources :conversations do
    resources :messages
  end

end

app/views/admins/get_user_profile.html.erb
  <div class=" jumbotron">
    <div class="admin-hd1">
      <div class="">
        Name: <%= @user_detail.first.user.name %>
      </div>
      <div class="">
          Email: <%= @user_detail.first.user.email %>
      </div>

    </div>
    <br>
    <div class="admin-hd1"> Requirements</div>
    <hr>
    <span class="">
      <% @user_detail.each do |detail| %>
        <div class="row">
          <div id="" class="col-md-4 ">
            <% if detail.floor_plan_image.present? %>
              <div>
                <%= image_tag attachment_url(detail, :floor_plan_image, :fill, 300, 300, format: "jpg"), rel: 'tooltip', title: 'Click to zoom', data: { 'placement': 'bottom' }, class: 'port-img img-thumbnail img-pop mytooltip' %>
              </div><!--slide content-->
            <% else %>
                No Floor Plan Image Shared <br>
            <% end %>
          </div>
          <div class="col-md-8 jumbotron">
            <div class="user_pre_hd1">
                <div> Budget: </div>
                <div class="user_pre_suhd1">
                <% if detail.budget == 1 %>
                  5 Lac and Under
                <% elsif detail.budget == 2 %>
                  10 Lac and Under
                <% elsif detail.budget == 3 %>
                  15 Lac and Under
                <% elsif detail.budget == 4 %>
                  15 Lac above
                <% else %>
                 NA
                <% end %>
              </div>
            </div>
            <br>
            <div class="user_pre_hd1">
                <div> Type of House: </div>
                <div class="user_pre_suhd1">
                  <% if detail.work_scope.present? %>
                    <%= detail.work_scope[0] %>
                  <% else %>
                    NA
                  <% end %>
                </div>
            </div>
            <br>
            <div class="user_pre_hd1">
                <div>  Spaces Interested : </div>
                <div class="user_pre_suhd1">
                  <% if detail.spaces.present? %>
                  <% Category.find(detail.spaces).each_with_index do |categ_id , index| %>
                    <!-- <label class="btn btn-primary"> -->
                      <% if index != 0 %>
                        ,
                      <% end %>
                      <%= categ_id.name %>
                    <!-- </label> -->
                  <% end %>
                  <% else %>
                    NA
                  <% end %>
                </div>
            </div>
            <br>
            <div class="user_pre_hd1">
              <div> Description : </div>
              <div class="user_pre_suhd1">
                <% if detail.description.present? %>
                  <%= detail.description %>
                <% else %>
                  NA
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <br>
        <div>
          <div class="admin-hd1">Designs</div>
          <% if FlatImage.where(user_detail_id: detail.id).present? %>
            <div class=" admins-user-profile-slider ">
              <!-- <%#= image_tag attachment_url(detail, :flat_image, :fill, 300, 300, format: "jpg"), data: { 'placement': 'bottom' }, class: 'port-img img-thumbnail' %> -->
              <% FlatImage.where(user_detail_id: detail.id).each do |img| %>
                <div>
                  
                  <% if img.file_content_type == "application/pdf" %>
                    <%= attachment_image_tag(img, :file, :fill, 300, 300 , class: ' img-thumbnail img-pop mytooltip', format: "jpg" ,  rel: 'tooltip', title: 'Click to zoom', data: { 'placement': 'bottom' })  %>
                    <%= link_to "Download file", attachment_url(img, :file, format: "pdf") %>
                  <% else %>
                      <%= attachment_image_tag(img, :file, :fill, 300, 300 , class: ' img-thumbnail img-pop mytooltip' ,  rel: 'tooltip', title: 'Click to zoom', data: { 'placement': 'bottom' })  %>
                  <% end %>

                </div>
              <% end %>
              <br>
            </div><!--preference slider-->
          <% else %>
              No Designs Shared
          <% end %>
        </div>


      <% end %>
    </span>
  </div>

  <div class="jumbotron">
    <div class="admin-hd1">Interests</div>
    <hr>
    <span class="">
      <%#= @user_profile.work_details %>
      <% if !@user_interest.empty? %>
        <% @questions.each do |ques| %>
          <div class="container">
            <div class="admin-main">
              <div class="admin-hd1"><%= ques.answer %></div><br>
              <div id="" class="admins-user-profile-slider ">
                <% @user_interest.where(question_id: ques.id).each do |catg_images| %>
                  <div>
                    <%= image_tag attachment_url(catg_images.category_item, :image, :fill, 300, 300, format: "jpg"), rel: 'tooltip', title: 'Click to zoom', data: { 'placement': 'bottom' }, class: 'port-img img-thumbnail img-pop mytooltip' %>

                  </div><!--slide content-->
                <% end %>
              </div><!--preference slider-->
            </div>
          </div>
        <% end %>
      <% end %>
    </span>
  </div><!--jumbo-->

  <div class=" jumbotron">
    <div class="admin-hd1">Favourate Products</div>
    <hr>
    <span class="admin-txt2">
      <%#= @user_profile.work_details %>
      <% if !@fav_products.empty? %>
          <div class="container">
            <div class="admin-main">
              <div id="" class="admins-user-profile-slider">
                <% @fav_products.each do |fav_product| %>
                  <div>
                    <%= image_tag attachment_url(fav_product.product, :product_image, :fill, 300, 300, format: "jpg"), rel: 'tooltip', title: 'Click to zoom', data: { 'placement': 'bottom' }, class: 'port-img img-thumbnail img-pop mytooltip' %>

                  </div><!--slide content-->
                <% end %>
              </div><!--preference slider-->
            </div>
          </div>
      <% else %>
        <div class="admin-hd1"><center>Not Available</center></div>
      <% end %>
    </span>
  </div><!--admin-main-jumbo-->

<script type="text/javascript">
var ready;
ready = function() {
  $('.admins-user-profile-slider').slick({
  dots: false,
  infinite: true,
  speed: 1000,
  slidesToShow: 3,
  slidesToScroll: 1,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 1,
        infinite: true,
        dots: false
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 1
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
  ]
});
}

// $(document).on('page:load', ready);
setTimeout(function(){
   ready();
}, 3000);

</script>

app/views/admins/guests.html.erb
<div class="container">
  <div class="admin-main-jumbo jumbotron">
    <div class="admin-hd1">All Users</div>
      <hr>
      <!-- Search Form starts here -->
      <%= search_form_for @search, url: users_admins_path(@search) do |f| %>
          <%= f.search_field :name_cont, placeholder: 'Name contains' %>
          <%= f.search_field :email_cont, placeholder: 'Email contains' %>
          <%= f.search_field :name_or_email_cont, placeholder: 'Name or Email contains' %>
        <span class="actions">
          <%= f.submit "Search", class: 'btn btn-sm btn-primary' %>
          <button type="button" onclick="clearForm();" class="btn btn-sm btn-default">Clear fields</button>
        </span>
      <% end %>

      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <!-- <th>Current Status</th> -->
            <!-- <th colspan="3"></th> -->
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr class="filter-user" data-user="<%= if user.activate then "active" else "inactive" end %>">
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.phone %></td>
              <!-- <td><#%= if user.activate then "active" else "inactive" end %></td>
              <td>
                <#% if user.activate %>
                  <#%= link_to 'Deactivate', status_admins_path(id: user.id, activate: false), class: 'btn btn-sm btn-danger' %>
                <#% else %>
                  <#%= link_to 'Activate', status_admins_path(id: user.id, activate: true), class: 'btn btn-sm btn-success' %>
                <#% end %>
              </td> -->
            </tr>
          <% end %>
        </tbody>
      </table>
      <center>
        <%= will_paginate @users, previous_label: h("<"), next_label: h(">"), renderer: BootstrapPagination::Rails %>
      </center>
    </div>
  </div>
<br>

app/views/admins/index.html.erb
<h1>Admins#index</h1>
<p>Find me in app/views/admins/index.html.erb</p>

app/views/admins/new_vendor.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="login-box">
        <%= form_for @user, url: create_vendor_admins_path(@user) do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
          <legend>Create New Vendor Account</legend>
          <%= f.hidden_field :role, value: 'vendor' %>

          <%= f.text_field :name, placeholder: 'Name', class: 'login-intxt form-control', required: true, autofocus: true %>
          <br><br>
          <%= f.email_field :email, type: 'email', placeholder: 'Email', class: 'login-intxt form-control', required: true, autofocus: true %>
          <br><br>
          <%= f.text_field :phone, type: 'number', placeholder: 'Phone', pattern: "[0-9]{9}", class: 'login-intxt form-control', required: true, autofocus: true %>
          <i class="text-muted">number without +91</i>
          <br><br>
          <%= f.password_field :password, placeholder: 'Password', class: 'login-intxt form-control', required: true, autocomplete: "off" %>
          <br><br>
          <%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'login-intxt form-control', required: true, autocomplete: "off" %>
          <br><br>
          <%= f.submit "Create", class: 'org-btn2 pad-btn btn' %>
        <% end %>
    </div>
  </div>
</div>
</div>
<br><br>

app/views/admins/users.html.erb
<div class="container">
  <div class="admin-main-jumbo jumbotron">
    <div class="admin-hd1">All Users</div>
      <hr>
      <!-- Search Form starts here -->
      <%= search_form_for @search, url: users_admins_path(@search) do |f| %>
          <%= f.search_field :name_cont, placeholder: 'Name contains' %>
          <%= f.search_field :email_cont, placeholder: 'Email contains' %>
          <%= f.search_field :name_or_email_cont, placeholder: 'Name or Email contains' %>
        <span class="actions">
          <%= f.submit "Search", class: 'btn btn-sm btn-primary' %>
          <button type="button" onclick="clearForm();" class="btn btn-sm btn-default">Clear fields</button>
        </span>
      <% end %>

      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <!-- <th>Current Status</th> -->
            <!-- <th colspan="3"></th> -->
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr class="filter-user" data-user="<%= if user.activate then "active" else "inactive" end %>">
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.phone %></td>
              <td>  <button type="button" class="btn btn-info btn-xs" data-toggle="" onclick="get_client_profile(<%= user.id %>)" data-target="#show_profile">View Profile</button> </td>
              <!-- <td><#%= if user.activate then "active" else "inactive" end %></td>
              <td>
                <#% if user.activate %>
                  <#%= link_to 'Deactivate', status_admins_path(id: user.id, activate: false), class: 'btn btn-sm btn-danger' %>
                <#% else %>
                  <#%= link_to 'Activate', status_admins_path(id: user.id, activate: true), class: 'btn btn-sm btn-success' %>
                <#% end %>
              </td> -->
            </tr>
          <% end %>
        </tbody>
      </table>
      <center>
        <%= will_paginate @users, previous_label: h("<"), next_label: h(">"), renderer: BootstrapPagination::Rails %>
      </center>

      <%= link_to 'Download User Data', export_users_admins_path(format: 'csv'), class: 'download-btn btn'%>
    </div>





  </div>
<!-- <div class="container">
  <div class="admin-main-jumbo jumbotron">
    <div class="" id="view_user_profile">
      <p>Some text in the modal.</p>
    </div>
  </div>
</div> -->


  <!-- Modal -->
  <div id="show_profile" class="modal fade col-sm-12" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">User Profile</h4>
        </div>
        <div class="modal-body" id="view_user_profile">
          <p>Some text in the modal.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

<br>

app/views/admins/vendors.html.erb
<div class="container">
  <div class="admin-main-jumbo jumbotron">
    <div class="admin-hd1">All Vendors</div><br>
    <span>
        <label for="">Filter vendor:</label>
        <select class="" id="vendors">
          <option value="all">Select</option>
          <option value="all">All</option>
          <option value="active">Active</option>
          <option value="inactive">Inactive</option>
        </select>
    </span>
      <hr>
      <!-- Search Form starts here -->
      <%= search_form_for @search, url: vendors_admins_path(@search) do |f| %>
          <%= f.search_field :name_cont, placeholder: 'Name contains' %>
          <%= f.search_field :email_cont, placeholder: 'Email contains' %>
          <%= f.search_field :name_or_email_cont, placeholder: 'Name or Email contains' %>
          <%= f.submit "Search", class: 'btn btn-sm btn-primary' %>
          <button type="button" onclick="clearForm();" class="btn btn-sm btn-default">Clear fields</button>
      <% end %>
      <br>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Blocked</th>
            <th>Current Status</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @vendors.each do |vendor| %>
            <tr class="filter-vendor" data-vendor="<%= if vendor.activate then "active" else "inactive" end %>">
              <td><%= vendor.name %></td>
              <td><%= vendor.email %></td>
              <td>
                <% if vendor.vendor_profile.selection_no == 3 %>
                  <%= link_to 'Unblock', unblock_admins_path(id: vendor.id), class: 'btn btn-sm btn-danger' %>
                <% else %>
                  No
                <% end %>
              </td>
              <td><%= if vendor.activate then "active" else "inactive" end %></td>
              <td>
                <% if vendor.activate %>
                  <%= link_to 'Deactivate', status_admins_path(id: vendor.id, activate: false), class: 'btn btn-sm btn-danger' %>
                <% else %>
                  <%= link_to 'Activate', status_admins_path(id: vendor.id, activate: true), class: 'btn btn-sm btn-success' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <center>
        <%= will_paginate @vendors, previous_label: h("<"), next_label: h(">"), renderer: BootstrapPagination::Rails %>
      </center>

      <%= link_to 'Create Vendor', new_vendor_admins_path, class: 'org-btn2 btn' %>
      <%= link_to 'Download Vendor Data', export_vendors_admins_path(format: 'csv'), class: 'download-btn btn'%>
    </div>
  </div>
<br>