config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :chat_data do
   collection do
    get 'get_chat_images'
    get 'get_user_profile'
    get 'update_conv_status'
    get 'get_project_phase'
   end
 end

 resources :tags
 resources :products
 resources :fav_products do
   collection do
    get 'remove_fav_prod'
   end
 end
 resources :huzzpa_works

 resources :blogs do
   collection do
     get 'get_blogby_category'
     get 'get_latest_blogs'
     get 'get_blogby_type'
     get 'admin_blog'
     get 'template'
   end
 end

 resources :comments, only: [:index, :create , :destroy]
 get '/comments/new/:parent_id', to: 'comments#new', as: :new_comment
 get '/comments/reply', to: 'comments#reply'

  get 'design/modular-kitchen-designers', to: 'design_inspiration#kitchen'
  get 'design-inspiration/kitchen' => redirect('design/modular-kitchen-designers')

  get 'design/modular-wardrobe-designers', to: 'design_inspiration#wardrobes'
  get 'design-inspiration/bed-room' => redirect('design/modular-wardrobe-designers')
  get 'design-inspiration/bed' => redirect('design/modular-wardrobe-designers')
  get 'design-inspiration/wardrobes' => redirect('design/modular-wardrobe-designers')

  get 'design/shoe-cabinet-designers', to: 'design_inspiration#shoe_cabinet'
  get 'design-inspiration/shoe-cabinet' => redirect('design/shoe-cabinet-designers')

  get 'design/study-unit-designers', to: 'design_inspiration#study'
  get 'design-inspiration/study-unit' => redirect('design/study-unit-designers')
  get 'design-inspiration/study' => redirect('design/study-unit-designers')

  get 'design/vanity-unit-designers', to: 'design_inspiration#vanity_unit'
  get 'design-inspiration/bath-room' => redirect('design/vanity-unit-designers')
  get 'design-inspiration/vanity-unit' => redirect('design/vanity-unit-designers')

  get 'design/tv-unit-designers', to: 'design_inspiration#tv_unit'
  get 'design-inspiration/living-room' => redirect('design/tv-unit-designers')
  get 'design-inspiration/tv-unit' => redirect('design/tv-unit-designers')

  get 'design/crockery-unit-designers', to: 'design_inspiration#crockery_unit'
  get 'design-inspiration/dining' => redirect('design/crockery-unit-designers')
  get 'design-inspiration/crockery-unit' => redirect('design/crockery-unit-designers')

  get 'design-inspiration/wall-treatment' => redirect('/')
  get 'design-inspiration/kids-bedroom' => redirect('/')
  get 'design-inspiration/balcony' => redirect('/')

  get '/questioners/get_category_item/:category_id',      to: 'questioners#get_category_item'

  get '/user_preferences/get_question/:current_seq_no',      to: 'user_preferences#get_question'

  get '/user_preferences/get_interest_questions',      to: 'user_preferences#get_interest_questions'

  get '/user_preferences/get_next_interest_question',      to: 'user_preferences#get_next_interest_question'

  get '/user_preferences/update_user_interest',      to: 'user_preferences#update_user_interest'

  get '/user_preferences/get_client_requirement',      to: 'user_preferences#get_client_requirement'

  post "question_sequences/activate_questions" => "question_sequences#activate_questions"

  post "question_sequences/deactivate_questions" => "question_sequences#deactivate_questions"

  get "question_sequences/update_sequence" => "question_sequences#update_sequence"

  get "chat_accesses/update_status" => "chat_accesses#update_status"

  get"matched_vendors/chat_request" => "matched_vendors@chat_request"

  get 'matched_vendors/:tab' => 'matched_vendors#index' , as: 'matched_recommendations'

  resources :admins do
    collection do
      get 'vendors'
      get 'status'
      get 'new_vendor'
      post 'create_vendor'
      get 'users'
      get 'unblock'
      get 'guests'
      get 'export_users'
      get 'export_vendors'
      get 'get_user_profile'
    end
  end

  resources :users, only: [] do
    collection do
      resources :preferences, only: [:index, :create], controller: 'user_preferences' do
        collection do
          get 'select'
          get 'selected'
        end
      end
    end
  end
  resources :vendor_preferences, only: [:index, :create] do
    collection do
      get 'select'
      get 'selected'
    end
  end

  resources :vendor_works do
    collection do
      get 'portfolio_images'
      get 'all'
    end
  end

  resources :matched_vendors do
    collection do
      post 'connect'
      post 'get_product_filter_by_categ'
    end
  end

  resources :matched_users do
    collection do
      post 'connect'
    end
  end

  resources :user_profiles, except: [:new]
  resources :vendor_profiles, except: [:new] do
    collection do
      get 'public/:id', to: 'vendor_profiles#public_profile', as: 'public'
    end
  end
  resources :types, except: [:show]
  resources :category_items, except: [:show]
  resources :categories
  resources :questions
  resources :questioners
  resources :user_interests
  resources :user_details
  resources :questioners
  resources :question_sequences
  resources :chat_accesses

  devise_for :users, controllers: {registrations: :registrations, sessions: "sessions",
                      omniauth_callbacks: 'omniauth_callbacks'}

  resources :guests

  root 'home#index'
  get 'about', to: 'home#about'
  get 'interior_designers_mumbai', to: 'home#designer_mumbai' , as: 'interior-designers-mumbai' ,  path: "interior-designers-mumbai"
  get 'mumbai' => redirect('interior-designers-mumbai')
  get 'interior_designers_mumbai' => redirect('interior-designers-mumbai')

  get 'our-portfolio', to: 'home#profile'
  get 'profile' => redirect('our-portfolio')
  post 'contact', to: 'home#contact_us'
  get 'privacy', to: 'home#privacy'
  get 'terms', to: 'home#terms'
  get 'faq', to: 'home#faq'
  get 'user-role', to: 'home#user_role'
  get 'vendor-role', to: 'home#vendor_role'
  get 'contact-us', to: 'home#contact'
  get 'contact_us' => redirect('contact-us')
  post 'subscribe', to: 'home#subscribe', as: :subscribe

  resources :activate_vendors do
    collection do
      get 'contact_admin'
    end
  end

  resources :conversations do
    resources :messages
  end

end

app/models/vendor_profile.rb
class VendorProfile < ActiveRecord::Base
  belongs_to :vendor, class_name: 'User', foreign_key: 'vendor_id'
  attachment :profile_image
  has_many :chat_accesses
end

app/controllers/vendor_profiles_controller.rb
# Vendor Profile Logic.
class VendorProfilesController < ApplicationController
  before_action :set_vendor_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:public_profile]
  before_action :authorize_vendor, except: [:public_profile]
  before_action :authorized_vendor, only: [:show, :edit, :update, :destroy]
  before_action :authorize_vendor_activation, except: [:public_profile]

  # GET /vendor_profiles
  # GET /vendor_profiles.json
  # def index
  #   @vendor_profiles = VendorProfile.all
  # end

  # GET /vendor_profiles/1
  # GET /vendor_profiles/1.json
  def show
  end

  # GET /vendor_profiles/new
  def new
    @vendor_profile = VendorProfile.new
  end

  # GET /vendor_profiles/1/edit
  def edit
  end

  # POST /vendor_profiles
  # POST /vendor_profiles.json
  def create
    @vendor_profile = current_user.build_vendor_profile(vendor_profile_params)
    # @vendor_profile

    respond_to do |format|
      if @vendor_profile.save
        format.html { redirect_to @vendor_profile, notice: 'Vendor profile was successfully created.' }
        format.json { render :show, status: :created, location: @vendor_profile }
      else
        format.html { render :new }
        format.json { render json: @vendor_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendor_profiles/1
  # PATCH/PUT /vendor_profiles/1.json
  def update
    respond_to do |format|
      if @vendor_profile.update(vendor_profile_params)
        format.html { redirect_to @vendor_profile, notice: 'Vendor profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor_profile }
      else
        format.html { render :edit }
        format.json { render json: @vendor_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendor_profiles/1
  # DELETE /vendor_profiles/1.json
  def destroy
    @vendor_profile.destroy
    respond_to do |format|
      format.html { redirect_to vendor_profiles_url, notice: 'Vendor profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def public_profile
    unless user_signed_in? && current_user.guest == true
      @vendor_id = params[:id]
      @vendor_details = User.includes(:vendor_works, :vendor_profile).where(id: @vendor_id).first
    else
      redirect_to edit_guest_path(current_user, vendor_id: params[:id])
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vendor_profile
    @vendor_profile = VendorProfile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vendor_profile_params
    params.require(:vendor_profile).permit(:company, :about, :address, :city, :vendor_id, :profile_image, :website, :experience, :pincode, :price_range)
  end

  def authorized_vendor
    redirect_to root_path, notice: 'You are not authorize to make this change' unless current_user == @vendor_profile.vendor
  end
end

app/helpers/vendor_profiles_helper.rb
module VendorProfilesHelper
  def get_chat_access(vendor_id)
      @vendorid = VendorProfile.where(vendor_id: vendor_id).first
     ChatAccess.where( user_id:  current_user.id , vendor_profile_id: @vendorid.id)
  end
end

app/views/vendor_profiles/_form.html.erb
<%= form_for(@vendor_profile) do |f| %>
  <% if @vendor_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor_profile.errors.count, "error") %> prohibited this vendor_profile from being saved:</h2>
      <ul>
      <% @vendor_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-4 mob-mgbtm">
      <span class="admin-txt">Company Name</span><br>
      <%= f.text_field :company, placeholder: 'Company', class: 'admin-intxt2 form-control' %>
    </div><!--col-sm-* end-->
    <div class="col-sm-4 mob-mgbtm">
      <span class="admin-txt">Company Website</span><br>
      <%= f.text_field :website, placeholder: 'website of the company', class: 'admin-intxt2 form-control' %>
    </div><!--col-sm-* end-->
    <div class="col-sm-4 mob-mgbtm">
      <span class="admin-txt">Profile Image</span><br>
      <%= f.attachment_field :profile_image, direct: true, presigned: true, class: 'admin-intxt2 form-group' %>
      <span id="vendorImage" class="hashtag"></span>
      <!-- <img src="" height="200" alt="Image preview..."> -->
    </div><!--col-sm-* end-->
  </div><!--row end-->
  <br>
  <div class="row">
    <div class="col-sm-4 mob-mgbtm">
      <span class="admin-txt2">Your Price Range</span><br>
        <%= f.select(:price_range, options_for_select([['5 lac & under', 500000], ['10 lac & under', 1000000], ['15 lac & under', 1500000], ['15 lac & above', 2000000]], @vendor_profile.price_range),{include_blank: "Select Price Range"}, class: 'admin-intxt2 form-control', required: true) %>
    </div><!--col-sm-* end-->
    <div class="col-sm-4 mob-mgbtm">
      <span class="admin-txt2">Experience</span><br>
        <%= f.select(:experience, options_for_select([['1 yr.', 1], ['2 yrs.', 2], ['3 yrs.', 3], ['4 yrs.', 4], ['5 yrs.', 5], ['6 yrs.', 6], ['7 yrs.', 7], ['8 yrs.', 8],['9 yrs.', 9], ['10+ yrs.', 10]], @vendor_profile.experience),{include_blank: "Select"}, class: 'admin-intxt2 form-control') %>
    </div><!--col-sm-* end-->
  </div><!--row end-->
  <br>
  <div class="row">
    <div class="col-sm-4 mob-mgbtm">
      <span class="admin-txt">Address</span><br>
      <%= f.text_area :address, class: 'admin-intxt2 form-control' %>
    </div><!--col-sm-* end-->
    <div class="col-sm-4 mob-mgbtm">
      <span class="admin-txt2">City</span><br>
        <%= f.select(:city, options_for_select([['Bangalore', 'Bangalore'], ['Chennai', 'Chennai'], ['Delhi', 'Delhi'], ['Hyderabad', 'Hyderabad'], ['Mumbai', 'Mumbai']], @vendor_profile.city),{include_blank: "Select your city"}, class: 'admin-intxt2 form-control', required: true) %>
    </div><!--col-sm-* end-->
    <div class="col-sm-4 mob-mgbtm">
      <span class="admin-txt">Pincode</span><br>
      <%= f.text_field :pincode, placeholder: 'pincode', type: 'number', class: 'admin-intxt2 form-control' %>
    </div><!--col-sm-* end-->
  </div>
  <br>
  <span class="admin-txt">About</span><br>
  <%= f.text_area :about, placeholder: 'Something interesting about you', class: 'admin-txtarea form-control', rows: '10' %>
  <!-- <span id="countchars"></span> -->
  <br><br>
  <div class="actions">
    <%= f.submit 'Save', class: 'org-btn2 btn' %>
    <%= link_to 'Cancel', vendor_profile_path(current_user.vendor_profile), class: 'grey-btn btn' %>
  </div>
<% end %>

app/views/vendor_profiles/edit.html.erb
<div class="container">
  <div class="admin-main-jumbo jumbotron">
    <div class="admin-hd1">Edit Profile</div>
    <hr>
    <br>
      <%= render 'form' %>
</div><!--admin-main-jumbo-->
</div><!--container end-->

app/views/vendor_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vendor Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>About</th>
      <th>Address</th>
      <th>Vendor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendor_profiles.each do |vendor_profile| %>
      <tr>
        <td><%= image_tag attachment_url(vendor_profile, :profile_image, :fill, 50, 50, format: 'jpg') %></td>
        <td><%= vendor_profile.company %></td>
        <td><%= vendor_profile.about %></td>
        <td><%= vendor_profile.address %></td>
        <td><%#= vendor_profile.vendor_id %></td>
        <td><%= link_to 'Show', vendor_profile %></td>
        <td><%= link_to 'Edit', edit_vendor_profile_path(vendor_profile) %></td>
        <td><%= link_to 'Destroy', vendor_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor profile', new_vendor_profile_path %>

app/views/vendor_profiles/new.html.erb
<h1>New Vendor Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', vendor_profiles_path %>

app/views/vendor_profiles/public_profile.html.erb
<!-- <#% @vendor_details.each do |vendor| %> -->
<% @title = "Huzzpa interior |Team |bangalore |mumbai" %>
<% @description= "We have passionate, knowledgeable and experienced interior design professionals are design excellence are committed to create customized   space with the undying spirit of collaboration and a practice of innovation" %>
  <div class="container">
    <div class="admin-main-jumbo jumbotron">
      <br><p id="notice"><%= notice %></p>
      <!-- <a href="interests"><span class="main-sugg-hd1">Interests /</span></a> -->
        <% if user_signed_in? && current_user.role == 'user' %>
          <%= link_to matched_vendors_path, class: ''  do %>
            <span class="main-sugg-hd1">Suggested Professionals /</span>
          <% end %>
        <% else %>
          <%= link_to all_vendor_works_path do %>
            <span class="main-sugg-hd1"> Back /</span>
          <% end %>
        <% end %>
      <span class="main-sugg-hd2"><%= @vendor_details.name %>'s Profile</span>

      <!-- <a href="suggvendors"></a> -->
      <!-- <a href="vendorsprofile"><span class="main-sugg-hd2">Madagascar</span></a> -->
      <hr class="myhr">
      <br>
      <div class="row">
        <div class="col-md-2" oncontextmenu="return false;">
          <% if !@vendor_details.vendor_profile.profile_image_id.nil?%>
            <%= image_tag attachment_url(@vendor_details.vendor_profile, :profile_image, :fill, 500, 500, format: 'png'), class: 'vendor-prof-img' %>
          <% else %>
            <%= image_tag "default.png",size: "200x200", class: ' thumbnail admin-prof-img'%>
          <% end %>
        </div>
        <div class="col-md-8">

          <div class="row">
            <div class="col-md-6 mob-mgbtm2">
              <div class="sugg-hd1"><%= @vendor_details.name %></div>
              <br>
              <span class="sugg-txt1">Location:</span><span class="sugg-txt2"><%= @vendor_details.vendor_profile.address %></span>
              <br><br>
              <span class="sugg-txt1">Company Name:</span><span class="sugg-txt2"><%= @vendor_details.vendor_profile.company %></span>
              <br><br>
              <span class="sugg-txt1">Experience:</span><span class="sugg-txt2"><%= @vendor_details.vendor_profile.experience %> yrs.</span>
            </div><!--div.col-md-* end-->
            <div class="col-md-6 mob-mgbtm2">
              <span class="sugg-txt1 pull-right">
                <!-- Allow connect only if user is signed in -->
                <% if user_signed_in? %>
                  <% chat_access = get_chat_access(@vendor_details.id) %>
                  <% if chat_access.present? %>
                    <% if chat_access[0].status %>
                        <label id="chat_allowed_lable" for="" class="btn vendor-sm-green-btn " >Connected for Chat</label>
                    <% else %>
                      <label id="chat_waiting_req_lable" for="" class="btn btn-warning" >Chat Requested</label>
                    <% end %>
                  <% else %>
                    <!-- Connect button for users -->
                    <%= form_tag(controller: "matched_vendors", action: "connect") do %>
                      <%= hidden_field_tag(:vendor_id, "#{@vendor_details.id}") %>
                      <span><%= button_tag(type: 'submit', class: 'green-btn btn pad-btn') do %>
                            Lets Connect &nbsp;<i class="fa fa-paper-plane"> </i>
                            <% end %>
                      </span>
                    <% end %>
                  <% end %>
                <% end %>
              </span>
              <!-- <span class="sugg-txt1">Website:</span><span class="sugg-txt2"><#%= vendor.vendor_profile.website %></span>
              <br><br>
              <span class="sugg-txt1">Email:</span><span class="sugg-txt2"><#%= vendor.email %></span>
              <br><br>
              <span class="sugg-txt1">Contact:</span><span class="sugg-txt2"><#%= vendor.phone %></span> -->
            </div>
            <!--div.col-md-* end-->
          </div><!--inner row-->
          <hr class="myhr">
          <div class="sugg-hd2">About Professional</div>
          <span class="admin-txt">
            <%= @vendor_details.vendor_profile.about %>
          </span>
          <br><br>
        </div><!--div.col-md-* end-->
      </div>
      <br><br>
      <div class="row" oncontextmenu="return false;">
        <div class="col-md-10 col-md-offset-1">
          <div class="vendor-public-preference-slider">
            <% @vendor_details.vendor_works.each do |vendor_works| %>
              <% vendor_works.vendor_portfolio_images.each do |images|%>
                <div>
                  <%= attachment_image_tag(images, :file, :fill, 500, 500, {class: 'exp-img port-img img-thumbnail'})%>
                  <br>
                </div><!--slide content-->
              <% end %>
            <% end %>
          </div><!--preference slider-->
        </div>
      </div>
    </div>
  </div>
<!-- <#% end %> -->

app/views/vendor_profiles/show.html.erb
<!-- <#%= image_tag attachment_url(@vendor_profile, :profile_image, :fill, 50, 50, format: 'jpg') %> -->

<div class="container">
  <div class="row">
    <div class="col-md-7">
      <div class="admin-main-jumbo jumbotron">
        <div class="admin-hd1">About</div>
        <hr>
        <span class="admin-txt2">
          <%= @vendor_profile.about %>
        </span>
      </div><!--admin-main-jumbo-->
    </div><!--col-md-* end-->
    <div class="col-md-5">
      <div class="admin-main-jumbo jumbotron">
        <div class="admin-hd1">Company</div>
        <hr>
        <table class="prof-comp-table">
          <tr>
            <td><i class="fa fa-briefcase"></i></td>
            <td><%= @vendor_profile.company %></td>
          </tr>
          <tr>
            <td><i class="fa fa-map-marker"></i></td>
            <td><%= @vendor_profile.address %></td>
          </tr>
          <tr>
            <td><i class="fa fa-map-marker"></i></td>
            <td><%= @vendor_profile.pincode %></td>
          </tr>
          <tr>
            <td><i class="fa fa-globe"></i></td>
            <td><%= @vendor_profile.website %></td>
          </tr>
        </table>
      </div><!--admin-main-jumbo-->
    </div><!--col-md-* end-->
  </div><!--row end-->
</div><!--container end-->