config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :chat_data do
   collection do
    get 'get_chat_images'
    get 'get_user_profile'
    get 'update_conv_status'
    get 'get_project_phase'
   end
 end

 resources :tags
 resources :products
 resources :fav_products do
   collection do
    get 'remove_fav_prod'
   end
 end
 resources :huzzpa_works

 resources :blogs do
   collection do
     get 'get_blogby_category'
     get 'get_latest_blogs'
     get 'get_blogby_type'
     get 'admin_blog'
     get 'template'
   end
 end

 resources :comments, only: [:index, :create , :destroy]
 get '/comments/new/:parent_id', to: 'comments#new', as: :new_comment
 get '/comments/reply', to: 'comments#reply'

  get 'design/modular-kitchen-designers', to: 'design_inspiration#kitchen'
  get 'design-inspiration/kitchen' => redirect('design/modular-kitchen-designers')

  get 'design/modular-wardrobe-designers', to: 'design_inspiration#wardrobes'
  get 'design-inspiration/bed-room' => redirect('design/modular-wardrobe-designers')
  get 'design-inspiration/bed' => redirect('design/modular-wardrobe-designers')
  get 'design-inspiration/wardrobes' => redirect('design/modular-wardrobe-designers')

  get 'design/shoe-cabinet-designers', to: 'design_inspiration#shoe_cabinet'
  get 'design-inspiration/shoe-cabinet' => redirect('design/shoe-cabinet-designers')

  get 'design/study-unit-designers', to: 'design_inspiration#study'
  get 'design-inspiration/study-unit' => redirect('design/study-unit-designers')
  get 'design-inspiration/study' => redirect('design/study-unit-designers')

  get 'design/vanity-unit-designers', to: 'design_inspiration#vanity_unit'
  get 'design-inspiration/bath-room' => redirect('design/vanity-unit-designers')
  get 'design-inspiration/vanity-unit' => redirect('design/vanity-unit-designers')

  get 'design/tv-unit-designers', to: 'design_inspiration#tv_unit'
  get 'design-inspiration/living-room' => redirect('design/tv-unit-designers')
  get 'design-inspiration/tv-unit' => redirect('design/tv-unit-designers')

  get 'design/crockery-unit-designers', to: 'design_inspiration#crockery_unit'
  get 'design-inspiration/dining' => redirect('design/crockery-unit-designers')
  get 'design-inspiration/crockery-unit' => redirect('design/crockery-unit-designers')

  get 'design-inspiration/wall-treatment' => redirect('/')
  get 'design-inspiration/kids-bedroom' => redirect('/')
  get 'design-inspiration/balcony' => redirect('/')

  get '/questioners/get_category_item/:category_id',      to: 'questioners#get_category_item'

  get '/user_preferences/get_question/:current_seq_no',      to: 'user_preferences#get_question'

  get '/user_preferences/get_interest_questions',      to: 'user_preferences#get_interest_questions'

  get '/user_preferences/get_next_interest_question',      to: 'user_preferences#get_next_interest_question'

  get '/user_preferences/update_user_interest',      to: 'user_preferences#update_user_interest'

  get '/user_preferences/get_client_requirement',      to: 'user_preferences#get_client_requirement'

  post "question_sequences/activate_questions" => "question_sequences#activate_questions"

  post "question_sequences/deactivate_questions" => "question_sequences#deactivate_questions"

  get "question_sequences/update_sequence" => "question_sequences#update_sequence"

  get "chat_accesses/update_status" => "chat_accesses#update_status"

  get"matched_vendors/chat_request" => "matched_vendors@chat_request"

  get 'matched_vendors/:tab' => 'matched_vendors#index' , as: 'matched_recommendations'

  resources :admins do
    collection do
      get 'vendors'
      get 'status'
      get 'new_vendor'
      post 'create_vendor'
      get 'users'
      get 'unblock'
      get 'guests'
      get 'export_users'
      get 'export_vendors'
      get 'get_user_profile'
    end
  end

  resources :users, only: [] do
    collection do
      resources :preferences, only: [:index, :create], controller: 'user_preferences' do
        collection do
          get 'select'
          get 'selected'
        end
      end
    end
  end
  resources :vendor_preferences, only: [:index, :create] do
    collection do
      get 'select'
      get 'selected'
    end
  end

  resources :vendor_works do
    collection do
      get 'portfolio_images'
      get 'all'
    end
  end

  resources :matched_vendors do
    collection do
      post 'connect'
      post 'get_product_filter_by_categ'
    end
  end

  resources :matched_users do
    collection do
      post 'connect'
    end
  end

  resources :user_profiles, except: [:new]
  resources :vendor_profiles, except: [:new] do
    collection do
      get 'public/:id', to: 'vendor_profiles#public_profile', as: 'public'
    end
  end
  resources :types, except: [:show]
  resources :category_items, except: [:show]
  resources :categories
  resources :questions
  resources :questioners
  resources :user_interests
  resources :user_details
  resources :questioners
  resources :question_sequences
  resources :chat_accesses

  devise_for :users, controllers: {registrations: :registrations, sessions: "sessions",
                      omniauth_callbacks: 'omniauth_callbacks'}

  resources :guests

  root 'home#index'
  get 'about', to: 'home#about'
  get 'interior_designers_mumbai', to: 'home#designer_mumbai' , as: 'interior-designers-mumbai' ,  path: "interior-designers-mumbai"
  get 'mumbai' => redirect('interior-designers-mumbai')
  get 'interior_designers_mumbai' => redirect('interior-designers-mumbai')

  get 'our-portfolio', to: 'home#profile'
  get 'profile' => redirect('our-portfolio')
  post 'contact', to: 'home#contact_us'
  get 'privacy', to: 'home#privacy'
  get 'terms', to: 'home#terms'
  get 'faq', to: 'home#faq'
  get 'user-role', to: 'home#user_role'
  get 'vendor-role', to: 'home#vendor_role'
  get 'contact-us', to: 'home#contact'
  get 'contact_us' => redirect('contact-us')
  post 'subscribe', to: 'home#subscribe', as: :subscribe

  resources :activate_vendors do
    collection do
      get 'contact_admin'
    end
  end

  resources :conversations do
    resources :messages
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :category
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter :authorize_admin

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)
    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tags_path, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name ,:category_id)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
      <%= f.label :name %><br>
    <%= f.text_field :name, class: 'login-intxt form-control full-width'  , :required => true %><br><br>
  </div>
  <div class="field">
      <%= f.label :category_id %><br>
      <%= f.select :category_id, options_for_select(Category.all.collect { |c| [c.name, c.id] }, @tag.category_id), { prompt: 'Select category' }, class: 'category-item login-intxt form-control' %><br><br>
  </div>

  <div class="actions">
    <%= f.submit "Create", class: 'org-btn2 pad-btn btn' %> <span><%= link_to 'Cancel', tags_path, class: 'cancel-btn pad-btn btn' %></span>
  </div>
<% end %>

app/views/tags/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="login-box">
        <h2>Edit Tags</h2>
        <hr>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>
<br><br>
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<div class="container">
  <div class="admin-main-jumbo jumbotron">
    <div class="admin-hd1">Tags</div>
      <hr>
      <%= link_to 'Add more', new_tag_path, class: 'org-btn2 btn' %>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Category</th>
            <!-- <th colspan="3"></th> -->
          </tr>
        </thead>

        <tbody>
         <% @tags.each do |tag| %>
            <tr>
              <td><%= tag.name %></td>
              <td><%= tag.category.name %></td>
              <!-- <td><#%= link_to 'Show', question %></td> -->
              <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
              <!-- <td><%= link_to 'Show', tag_path(tag)%> -->
              <!-- <td><%#= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>


<%#= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="login-box">
        <h2>New Tags</h2>
        <hr>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>
<br><br>
<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>