config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :chat_data do
   collection do
    get 'get_chat_images'
    get 'get_user_profile'
    get 'update_conv_status'
    get 'get_project_phase'
   end
 end

 resources :tags
 resources :products
 resources :fav_products do
   collection do
    get 'remove_fav_prod'
   end
 end
 resources :huzzpa_works

 resources :blogs do
   collection do
     get 'get_blogby_category'
     get 'get_latest_blogs'
     get 'get_blogby_type'
     get 'admin_blog'
     get 'template'
   end
 end

 resources :comments, only: [:index, :create , :destroy]
 get '/comments/new/:parent_id', to: 'comments#new', as: :new_comment
 get '/comments/reply', to: 'comments#reply'

  get 'design/modular-kitchen-designers', to: 'design_inspiration#kitchen'
  get 'design-inspiration/kitchen' => redirect('design/modular-kitchen-designers')

  get 'design/modular-wardrobe-designers', to: 'design_inspiration#wardrobes'
  get 'design-inspiration/bed-room' => redirect('design/modular-wardrobe-designers')
  get 'design-inspiration/bed' => redirect('design/modular-wardrobe-designers')
  get 'design-inspiration/wardrobes' => redirect('design/modular-wardrobe-designers')

  get 'design/shoe-cabinet-designers', to: 'design_inspiration#shoe_cabinet'
  get 'design-inspiration/shoe-cabinet' => redirect('design/shoe-cabinet-designers')

  get 'design/study-unit-designers', to: 'design_inspiration#study'
  get 'design-inspiration/study-unit' => redirect('design/study-unit-designers')
  get 'design-inspiration/study' => redirect('design/study-unit-designers')

  get 'design/vanity-unit-designers', to: 'design_inspiration#vanity_unit'
  get 'design-inspiration/bath-room' => redirect('design/vanity-unit-designers')
  get 'design-inspiration/vanity-unit' => redirect('design/vanity-unit-designers')

  get 'design/tv-unit-designers', to: 'design_inspiration#tv_unit'
  get 'design-inspiration/living-room' => redirect('design/tv-unit-designers')
  get 'design-inspiration/tv-unit' => redirect('design/tv-unit-designers')

  get 'design/crockery-unit-designers', to: 'design_inspiration#crockery_unit'
  get 'design-inspiration/dining' => redirect('design/crockery-unit-designers')
  get 'design-inspiration/crockery-unit' => redirect('design/crockery-unit-designers')

  get 'design-inspiration/wall-treatment' => redirect('/')
  get 'design-inspiration/kids-bedroom' => redirect('/')
  get 'design-inspiration/balcony' => redirect('/')

  get '/questioners/get_category_item/:category_id',      to: 'questioners#get_category_item'

  get '/user_preferences/get_question/:current_seq_no',      to: 'user_preferences#get_question'

  get '/user_preferences/get_interest_questions',      to: 'user_preferences#get_interest_questions'

  get '/user_preferences/get_next_interest_question',      to: 'user_preferences#get_next_interest_question'

  get '/user_preferences/update_user_interest',      to: 'user_preferences#update_user_interest'

  get '/user_preferences/get_client_requirement',      to: 'user_preferences#get_client_requirement'

  post "question_sequences/activate_questions" => "question_sequences#activate_questions"

  post "question_sequences/deactivate_questions" => "question_sequences#deactivate_questions"

  get "question_sequences/update_sequence" => "question_sequences#update_sequence"

  get "chat_accesses/update_status" => "chat_accesses#update_status"

  get"matched_vendors/chat_request" => "matched_vendors@chat_request"

  get 'matched_vendors/:tab' => 'matched_vendors#index' , as: 'matched_recommendations'

  resources :admins do
    collection do
      get 'vendors'
      get 'status'
      get 'new_vendor'
      post 'create_vendor'
      get 'users'
      get 'unblock'
      get 'guests'
      get 'export_users'
      get 'export_vendors'
      get 'get_user_profile'
    end
  end

  resources :users, only: [] do
    collection do
      resources :preferences, only: [:index, :create], controller: 'user_preferences' do
        collection do
          get 'select'
          get 'selected'
        end
      end
    end
  end
  resources :vendor_preferences, only: [:index, :create] do
    collection do
      get 'select'
      get 'selected'
    end
  end

  resources :vendor_works do
    collection do
      get 'portfolio_images'
      get 'all'
    end
  end

  resources :matched_vendors do
    collection do
      post 'connect'
      post 'get_product_filter_by_categ'
    end
  end

  resources :matched_users do
    collection do
      post 'connect'
    end
  end

  resources :user_profiles, except: [:new]
  resources :vendor_profiles, except: [:new] do
    collection do
      get 'public/:id', to: 'vendor_profiles#public_profile', as: 'public'
    end
  end
  resources :types, except: [:show]
  resources :category_items, except: [:show]
  resources :categories
  resources :questions
  resources :questioners
  resources :user_interests
  resources :user_details
  resources :questioners
  resources :question_sequences
  resources :chat_accesses

  devise_for :users, controllers: {registrations: :registrations, sessions: "sessions",
                      omniauth_callbacks: 'omniauth_callbacks'}

  resources :guests

  root 'home#index'
  get 'about', to: 'home#about'
  get 'interior_designers_mumbai', to: 'home#designer_mumbai' , as: 'interior-designers-mumbai' ,  path: "interior-designers-mumbai"
  get 'mumbai' => redirect('interior-designers-mumbai')
  get 'interior_designers_mumbai' => redirect('interior-designers-mumbai')

  get 'our-portfolio', to: 'home#profile'
  get 'profile' => redirect('our-portfolio')
  post 'contact', to: 'home#contact_us'
  get 'privacy', to: 'home#privacy'
  get 'terms', to: 'home#terms'
  get 'faq', to: 'home#faq'
  get 'user-role', to: 'home#user_role'
  get 'vendor-role', to: 'home#vendor_role'
  get 'contact-us', to: 'home#contact'
  get 'contact_us' => redirect('contact-us')
  post 'subscribe', to: 'home#subscribe', as: :subscribe

  resources :activate_vendors do
    collection do
      get 'contact_admin'
    end
  end

  resources :conversations do
    resources :messages
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_items
  has_many :tags
  has_many :questioners
  attachment :profile_image
  has_many :blogs
end

app/controllers/categories_controller.rb
# Category Controller
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter :authorize_admin

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name, :profile_image, :form_option)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'login-intxt full-width form-control' , :required => true %><br><br>
  </div>
  <div class="field">
    <%= f.label 'Image' %><br>
    <%= f.attachment_field :profile_image, direct: true, presigned: true , :required => true , class: 'form-group'  %> <br>
  </div>
  <div class="field">
   <%= f.label :form_option %><br />
   <%= f.label :form_option, "Yes", :value => "true"  %>
   <%= f.radio_button :form_option, true %>
   <%= f.label :form_option, "No", :value => "false" %>
   <%= f.radio_button :form_option, false, :checked => true %>
    <br><br>
    <!-- <%= radio_button_tag(:form_option, "true") %> True <%= radio_button_tag(:form_option, "false")%> False<br><br> -->
  </div>


  <div class="actions">
    <%= f.submit "Create", class: 'org-btn2 pad-btn btn' %> <span><%= link_to 'Cancel', categories_path, class: 'cancel-btn pad-btn btn' %></span>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="login-box">
        <h2>Editing Category</h2>
        <hr>
        <%= form_for(@category) do |f| %>
          <% if @category.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

              <ul>
              <% @category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name, class: 'login-intxt full-width form-control' , :required => true %><br><br>
          </div>
          <div class="field">
            <%= f.label 'Image' %> (Optional)<br>
            <%= f.attachment_field :profile_image, direct: true, presigned: true  , class: 'form-group'  %> <br>
          </div>
          <div class="field">
            
           <%= f.label :form_option %><br />
           <% if @category.form_option %>
             <%= f.label :form_option, "Yes", :value => "true"  %>
             <%= f.radio_button :form_option, true  , :checked => true %>
             <%= f.label :form_option, "No", :value => "false" %>
             <%= f.radio_button :form_option, false, :checked => false %>
            <% else %>
              <%= f.label :form_option, "Yes", :value => "true"  %>
              <%= f.radio_button :form_option, true   %>
              <%= f.label :form_option, "No", :value => "false" %>
              <%= f.radio_button :form_option, false, :checked => true %>
            <% end %>
            <br><br>
            <!-- <%= radio_button_tag(:form_option, "true") %> True <%= radio_button_tag(:form_option, "false")%> False<br><br> -->
          </div>

          <div class="actions">
            <%= f.submit "Update", class: 'org-btn2 pad-btn btn' %> <span><%= link_to 'Cancel', categories_path, class: 'cancel-btn pad-btn btn' %></span>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>
<br><br>

app/views/categories/index.html.erb
<div class="container">
  <div class="admin-main-jumbo jumbotron">
    <div class="admin-hd1">All Categories</div>
      <hr>
    <p id="notice"><%= notice %></p>
    <%= link_to 'Add more', new_category_path, class: 'org-btn2 btn' %>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Form Option</th>
            <!-- <th colspan="3"></th> -->
          </tr>
        </thead>

        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td><%= category.form_option %></td>
              <!-- <td><#%= link_to 'Show', category %></td> -->
              <td><%= link_to 'Edit', edit_category_path(category) %></td>
              <td><%= link_to 'Show', category_path(category)%>
              <!-- <td><%#= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>



<br>

app/views/categories/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="login-box">
        <h2>New Category</h2>
        <hr>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>
<br><br>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4 mob-mgbtm">
      <div class="sugg-box img-thumbnail">
        <%= image_tag attachment_url(@category, :profile_image, :fill, 300, 300, format: "jpg")%>
        <br>
        <span>Category: <%= @category.name %></span><br>
        <span>
          <%= link_to 'Edit', edit_category_path(@category) %> |
          <%= link_to 'Back', categories_path %>
        </span>
      </div>
    </div>
  </div>
</div>